Repository SCRT-HQ/PSGSuite, pull requests merged in 2018-06, with the labels that each got.

#52 !build v2.6.3 - resolve issue #51
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Drive/Export-GSDriveFile.ps1
  README.md
Labels: bug

#58 Add Get-GSCalendarACL and New-GSCalendarACL
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Calendar/Get-GSCalendarACL.ps1
  PSGSuite/Public/Calendar/New-GSCalendarACL.ps1
  README.md
Labels: enhancement, work in progress

#61 pushing fixes for issue #59
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Calendar/Update-GSCalendarEvent.ps1
  README.md
Labels: bug, work in progress

#64 Add a Function to Remove Drive Permisison
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Drive/Remove-GSDrivePermission.ps1
  README.md
Labels: work in progress

#65 fix for issue #63
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Groups/Get-GSGroup.ps1
  README.md
Labels: bug, work in progress
