Repository SCRT-HQ/PSGSuite, pull requests merged in 2018-10, with the labels that each got.

#88 !build v2.14.1 with Classroom function fixes
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Classroom/Get-GSCourse.ps1
  PSGSuite/Public/Classroom/Get-GSCourseParticipant.ps1
  PSGSuite/Public/Classroom/Get-GSStudentGuardianInvitation.ps1
  README.md
Labels: bug, work in progress

#89 v2.15.0 with updated Gmail Delegation functions
  CHANGELOG.md
  PSGSuite/Aliases/PSGSuite.Aliases.ps1
  PSGSuite/PSGSuite.psd1
  PSGSuite/PSGSuite.psm1
  PSGSuite/Public/Delegation/Add-GSGmailDelegate.ps1
  PSGSuite/Public/Delegation/Get-GSGmailDelegate.ps1
  PSGSuite/Public/Delegation/Get-GSGmailDelegates.ps1
  PSGSuite/Public/Delegation/Remove-GSGmailDelegate.ps1
  README.md
Labels: enhancement, work in progress

#92 !build v2.15.1 for #87 and #90
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Private/Get-MimeType.ps1
  PSGSuite/Public/Classroom/Add-GSCourseParticipant.ps1
  PSGSuite/Public/Classroom/Get-GSCourse.ps1
  PSGSuite/Public/Classroom/Get-GSCourseAlias.ps1
  PSGSuite/Public/Classroom/Get-GSCourseInvitation.ps1
  PSGSuite/Public/Classroom/Get-GSCourseParticipant.ps1
  PSGSuite/Public/Classroom/Get-GSStudentGuardian.ps1
  PSGSuite/Public/Classroom/Get-GSStudentGuardianInvitation.ps1
  PSGSuite/Public/Classroom/New-GSCourse.ps1
  PSGSuite/Public/Classroom/New-GSCourseAlias.ps1
  PSGSuite/Public/Classroom/New-GSCourseInvitation.ps1
  PSGSuite/Public/Classroom/New-GSStudentGuardianInvitation.ps1
  PSGSuite/Public/Classroom/Remove-GSCourse.ps1
  PSGSuite/Public/Classroom/Remove-GSCourseAlias.ps1
  PSGSuite/Public/Classroom/Remove-GSCourseInvitation.ps1
  PSGSuite/Public/Classroom/Remove-GSCourseParticipant.ps1
  PSGSuite/Public/Classroom/Remove-GSStudentGuardian.ps1
  PSGSuite/Public/Classroom/Update-GSCourse.ps1
  PSGSuite/Public/Users/Get-GSUserPhoto.ps1
  PSGSuite/Public/Users/Remove-GSUserPhoto.ps1
  PSGSuite/Public/Users/Update-GSUserPhoto.ps1
  README.md
Labels: bug, enhancement, work in progress

#94 2.15.2
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Gmail/Remove-GSGmailMessage.ps1
  PSGSuite/Public/Gmail/Update-GSGmailLabel.ps1
  PSGSuite/Public/Gmail/Update-GSGmailMessageLabel.ps1
  README.md
Labels: enhancement, work in progress

#95 !build v2.15.3 with updates for #87 and #93
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Classroom/Add-GSCourseParticipant.ps1
  PSGSuite/Public/Classroom/Get-GSClassroomUserProfile.ps1
  PSGSuite/Public/Classroom/Get-GSCourseParticipant.ps1
  PSGSuite/Public/Gmail/Remove-GSGmailMessage.ps1
  PSGSuite/Public/Gmail/Update-GSGmailMessageLabels.ps1
  PSGSuite/Public/Users/Get-GSUser.ps1
  README.md
Labels: bug, enhancement, work in progress

#97 !build v2.15.4 with updates and private function cleanup
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Private/ListPrivate/Get-GSGroupListPrivate.ps1
  PSGSuite/Private/ListPrivate/Get-GSUserListPrivate.ps1
  PSGSuite/Public/Gmail/Get-GSGmailMessageList.ps1
  PSGSuite/Public/Groups/Get-GSGroup.ps1
  PSGSuite/Public/Users/Get-GSUser.ps1
  README.md
Labels: enhancement, work in progress

#98 Updates to build scripts to compile PSM1 during CI/CD
  .gitignore
  CHANGELOG.md
  DebugMode.ps1
  PSGSuite/PSGSuite.psd1
  PSGSuite/PSGSuite.psm1
  PSGSuite/Private/Import-SpecificConfiguration.ps1
  PSGSuite/Private/ListPrivate/Get-GSShortUrlListPrivate.ps1
  PSGSuite/Public/Calendar/New-GSCalendarACL.ps1
  PSGSuite/Public/Data Transfer/Start-GSDataTransfer.ps1
  PSGSuite/Public/Drive/Copy-GSDriveFile.ps1
  PSGSuite/Public/Drive/Export-GSDriveFile.ps1
  PSGSuite/Public/Drive/Get-GSDriveFile.ps1
  PSGSuite/Public/Drive/New-GSDriveFile.ps1
  PSGSuite/Public/Groups/Get-GSGroupMember.ps1
  README.md
  Tests/PSGSuite.Mock.Tests.ps1
  Tests/PSGSuite.Tests.ps1
  ci/WikiUpdater.ps1
  ci/init.ps1
  ci/psake.ps1
Labels: enhancement, work in progress

#99 Feature/pester updates and module compilation
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  README.md
  ci/download.sh
  ci/psake.ps1
Labels: bug, work in progress

#100 updated module build script and tests
  ci/psake.ps1
Labels: bug, work in progress

#104 !build v2.17.0 with updated psake, functions, and fixes for #102 and #103
  .gitignore
  .travis.yml
  CHANGELOG.md
  DebugMode.ps1
  PSGSuite/PSGSuite.psd1
  PSGSuite/PSGSuite.psm1
  PSGSuite/Public/Authentication/Get-GSToken.ps1
  PSGSuite/Public/Authentication/New-GoogleService.ps1
  PSGSuite/Public/Drive/Add-GSDrivePermission.ps1
  PSGSuite/Public/Users/Get-GSUser.ps1
  README.md
  Tests/Mocks/Users.Mocks.ps1
  Tests/Module Tests/PSGSuite.Tests.ps1
  Tests/PSGSuite.Mock.Tests.ps1
  Tests/Unit Tests/Users/PSGSuite.Get-GSUser.Tests.ps1
  appveyor.yml
  azure-pipelines.yml
  build.ps1
  ci/pwsh.build.ps1
  psake.ps1
  pwsh_download.sh
Labels: bug, enhancement, work in progress

#105 !build v2.17.0 with updates for #102 and #103 and test Azure Pipelines yml
  azure-pipelines.yml
Labels: work in progress

#106 !build v2.17.1 to validate Azure Pipelines deployment
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  README.md
  azure-pipelines.yml
  build.ps1
  psake.ps1
Labels: work in progress

#107 !deploy v2.17.2 with fixes for issue #103
  .gitignore
  .travis.yml
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/PSGSuite.psm1
  PSGSuite/Public/Drive/Add-GSDrivePermission.ps1
  README.md
  Tests/Module Tests/PSGSuite.Tests.ps1
  appveyor.yml
  azure-pipelines.yml
  build.ps1
  psake.ps1
Labels: bug, work in progress
