Repository SCRT-HQ/PSGSuite, pull requests merged in 2018-12, with the labels that each got.

#130 Add Support for User Relation
  PSGSuite/Public/Helpers/Add-GSUserRelation.ps1
  PSGSuite/Public/Users/New-GSUser.ps1
  PSGSuite/Public/Users/Update-GSUser.ps1
Labels: work in progress

#134 pushing updates for v2.21.0
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Helpers/Add-GSUserRelation.ps1
  PSGSuite/Public/Sheets/Get-GSSheetInfo.ps1
  PSGSuite/Public/Users/Update-GSUser.ps1
  README.md
Labels: bug, enhancement, work in progress

#135 adding content for v2.21.1
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Authentication/Get-GSToken.ps1
  PSGSuite/Public/Authentication/New-GoogleService.ps1
  PSGSuite/Public/Configuration/Get-PSGSuiteConfig.ps1
  PSGSuite/Public/Configuration/Set-PSGSuiteConfig.ps1
  PSGSuite/Public/Configuration/Switch-PSGSuiteConfig.ps1
  README.md
  build.ps1
Labels: bug, enhancement, work in progress

#137 v2.21.2 - fix for #136
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Drive/Start-GSDriveFileUpload.ps1
  README.md
Labels: bug, work in progress

#139 v2.22.0 - enhanced PSGSuiteConfig management and portability
  .gitignore
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Authentication/New-GoogleService.ps1
  PSGSuite/Public/Configuration/Export-PSGSuiteConfig.ps1
  PSGSuite/Public/Configuration/Get-PSGSuiteConfig.ps1
  PSGSuite/Public/Configuration/Import-PSGSuiteConfig.ps1
  PSGSuite/Public/Configuration/Set-PSGSuiteConfig.ps1
  PSGSuite/Public/Configuration/Switch-PSGSuiteConfig.ps1
  README.md
  psake.ps1
Labels: enhancement, work in progress

#141 2.22.1
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Calendar/Get-GSCalendarSubscription.ps1
  PSGSuite/Public/Drive/Remove-GSDriveFile.ps1
  README.md
Labels: enhancement, work in progress

#143 updated CI/CD assets
  Tests/0. Mocks/Core.Mocks.ps1
  Tests/0. Mocks/DirectoryService.Mocks.ps1
  Tests/1. Module Tests/PSGSuite.Module.Tests.ps1
  Tests/2. Unit Tests/Users/PSGSuite.Get-GSUser.Tests.ps1
  Tests/2. Unit Tests/Users/PSGSuite.New-GSUser.Tests.ps1
  Tests/3. Integration Tests/PSGSuite.Integration.Tests.ps1
  azure-pipelines.yml
  psake.ps1
Labels: enhancement, work in progress
