Repository SCRT-HQ/PSGSuite, pull requests merged in 2019-04, with the labels that each got.

#174 Update Get-GSDriveFileList.ps1
  PSGSuite/Public/Drive/Get-GSDriveFileList.ps1
Labels: bug, work in progress

#176 v2.26.1
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Authentication/New-GoogleService.ps1
  PSGSuite/Public/Drive/Get-GSDriveFileList.ps1
  PSGSuite/Public/Drive/New-GSDriveFile.ps1
  PSGSuite/Public/Drive/Update-GSDriveFile.ps1
  PSGSuite/lib/net45/Google.Apis.Drive.v3.dll
  PSGSuite/lib/netstandard1.3/Google.Apis.Drive.v3.dll
  README.md
Labels: bug, enhancement, work in progress

#181 v2.26.2 adding features and squashing bugs
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Private/ListPrivate/Get-GSUserLicenseListPrivate.ps1
  PSGSuite/Public/Authentication/Clear-PSGSuiteServiceCache.ps1
  PSGSuite/Public/Authentication/Get-PSGSuiteServiceCache.ps1
  PSGSuite/Public/Authentication/New-GoogleService.ps1
  PSGSuite/Public/Drive/Get-GSDriveFileList.ps1
  PSGSuite/Public/Drive/Start-GSDriveFileUpload.ps1
  PSGSuite/Public/Gmail/New-GSGmailSMIMEInfo.ps1
  PSGSuite/Public/Helpers/Add-GSEventAttendee.ps1
  PSGSuite/Public/Helpers/Add-GSGmailSmtpMsa.ps1
  PSGSuite/Public/Helpers/Add-GSUserAddress.ps1
  PSGSuite/Public/Helpers/Add-GSUserEmail.ps1
  PSGSuite/Public/Helpers/Add-GSUserExternalId.ps1
  PSGSuite/Public/Helpers/Add-GSUserIm.ps1
  PSGSuite/Public/Helpers/Add-GSUserLocation.ps1
  PSGSuite/Public/Helpers/Add-GSUserOrganization.ps1
  PSGSuite/Public/Helpers/Add-GSUserPhone.ps1
  PSGSuite/Public/Helpers/Add-GSUserRelation.ps1
  PSGSuite/Public/Helpers/Add-GSUserSchemaField.ps1
  PSGSuite/Public/Licensing/Get-GSUserLicense.ps1
  PSGSuite/Public/Users/New-GSUser.ps1
  PSGSuite/Public/Users/Update-GSUser.ps1
  PSGSuite/lib/net45/Google.Apis.Gmail.v1.dll
  PSGSuite/lib/netstandard1.3/Google.Apis.Gmail.v1.dll
  README.md
Labels: bug, enhancement, work in progress

#183 pushing up v2.26.3 with fix for #182
  CHANGELOG.md
  PSGSuite/PSGSuite.psd1
  PSGSuite/Public/Drive/Add-GSDrivePermission.ps1
  README.md
Labels: enhancement
